#
# Build stage
#
FROM openjdk:11-jdk-slim AS build

COPY .mvn /home/app/.mvn
COPY tasks-client /home/app/tasks-client
COPY tasks-server /home/app/tasks-server
COPY mvnw /home/app/
COPY pom.xml /home/app/
WORKDIR /home/app
RUN ./mvnw clean package

#
# Package stage
#
FROM openjdk:11-jre-slim

COPY --from=build /home/app/tasks-server/target/tasks-server-0.0.1-SNAPSHOT.jar /home/app/tasks-server.jar
COPY tasks-server/api /home/app/api
COPY tasks-server/entrypoint.sh /home/app
WORKDIR /home/app
RUN chmod +x ./entrypoint.sh
EXPOSE 8080
CMD ["./entrypoint.sh"]